package org.neuronavx.logger

import android.content.Context
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.neuronavx.logger.nav.Alignment
import org.neuronavx.logger.nav.FieldBlackoutPhase
import org.neuronavx.logger.nav.FieldBlackoutTest
import org.neuronavx.logger.nav.GnssFix
import org.neuronavx.logger.nav.HeadingRateSource
import org.neuronavx.logger.nav.LiveSpeedAdapter
import org.neuronavx.logger.nav.NavMode
import org.neuronavx.logger.nav.Navigator
import org.neuronavx.logger.nav.OnlineCalibration
import org.neuronavx.logger.nav.ReplaySource
import org.neuronavx.logger.nav.RuntimeConfig
import org.neuronavx.logger.nav.SpeedEstimate
import org.neuronavx.logger.nav.SpeedModel
import org.neuronavx.logger.nav.SpeedPredictionModel
import kotlin.math.abs
import kotlin.math.cos
import kotlin.math.hypot
import kotlin.math.sin
import kotlin.math.sqrt

/**
 * The Android estimator is a second implementation of a pipeline that already works on the
 * desktop, and a second implementation that is never compared against the first is a
 * liability. These tests replay a log through the on-device loop and check it against the
 * desktop's answer on the identical file.
 *
 * The reference is generated by `scripts/make_replay_log.py`, configured so the desktop run
 * uses only what a live system could know: the outage is detected from GNSS health rather
 * than handed over as a mask.
 */
@RunWith(AndroidJUnit4::class)
class NavigationParityTest {

    private data class ReplayFixture(
        val label: String,
        val csvAsset: String,
        val sidecarAsset: String,
        /** The signature demo is an app asset; extra parity routes belong only to tests. */
        val csvShipsWithApp: Boolean = false,
    )

    /** The app under test: owns the shipped model and its runtime config. */
    private val context: Context
        get() = InstrumentationRegistry.getInstrumentation().targetContext

    /** The test APK: owns the replay log and its reference answer. */
    private val testContext: Context
        get() = InstrumentationRegistry.getInstrumentation().context

    private fun replay(fixture: ReplayFixture = M_SEG00) =
        (if (fixture.csvShipsWithApp) context else testContext).assets.open(fixture.csvAsset)

    private fun sidecar(fixture: ReplayFixture = M_SEG00): JSONObject =
        testContext.assets.open(fixture.sidecarAsset).bufferedReader()
        .use { JSONObject(it.readText()) }

    private fun desktopAlignment(fixture: ReplayFixture = M_SEG00): Alignment {
        val a = sidecar(fixture).getJSONObject("alignment")
        return Alignment(
            forwardAngleRad = a.getDouble("forward_angle_rad"),
            forwardAccelScale = a.getDouble("forward_accel_scale"),
            gyroBiasRadS = a.getDouble("gyro_bias_rad_s"),
            yawChannel = a.getInt("yaw_channel"),
            yawScale = a.getDouble("yaw_scale"),
            forwardAccelCorr = Double.NaN, yawCorr = Double.NaN,
            samples = 0, baselines = 0,
        )
    }

    /**
     * The whole loop, given the calibration the desktop settled on.
     *
     * Fixing the calibration is deliberate: it isolates the port of the signals, features,
     * standardisation, network and filter from the separate question of whether the online
     * calibration converges to the same constants, which the next test asks. Debugging a
     * single end-to-end number that folds both together is how ports stay broken.
     */
    @Test
    fun replayReproducesDesktopTrajectory() {
        assertReplayMatchesDesktop(M_SEG00)
    }

    /**
     * The original parity result was one route from one driver. These two fixtures make a
     * behavioural change cross a second route and a second phone/vehicle before it can pass.
     * They live in the test APK so production still ships only the signature demo drive.
     */
    @Test
    fun additionalRoutesReproduceDesktopTrajectories() {
        for (fixture in listOf(M_SEG01, S1_SEG00)) assertReplayMatchesDesktop(fixture)
    }

    private fun assertReplayMatchesDesktop(fixture: ReplayFixture) {
        val runtime = RuntimeConfig.fromAsset(context)
        val answer = sidecar(fixture)
        val expected = answer.getJSONObject("desktop")
        val blackout = answer.getJSONObject("blackout")
        val exitRow = blackout.getInt("last_row")

        SpeedModel(context, runtime).use { model ->
            val navigator = Navigator(runtime, model)
            navigator.overrideCalibration(desktopAlignment(fixture))
            // Pin the local frame to the desktop's origin. Live, the phone picks its own
            // from the first fix, which is a few metres away because that fix carries
            // noise; comparing two trajectories expressed in different frames would fold a
            // constant offset into every number here.
            val origin = answer.getJSONArray("origin_lat_lon_alt")
            navigator.setOrigin(origin.getDouble(0), origin.getDouble(1), origin.getDouble(2))

            val trackStride = expected.getInt("track_stride")
            val track = expected.getJSONArray("track_enu")
            var worstRow = -1
            var worstGap = 0.0
            var firstDivergeRow = -1
            val earlyGaps = StringBuilder()

            var atExit: Navigator.State? = null
            var last: Navigator.State? = null
            var sawBlackout = false
            var emitted = 0
            // Count CSV ROWS, not emitted states: the navigator produces nothing until
            // calibration is settled, so the two indices are not the same and the sidecar
            // indexes rows.
            var row = -1
            ReplaySource(replay(fixture)).use { source ->
                while (true) {
                    val sample = source.next() ?: break
                    row++
                    val state = navigator.addSample(
                        sample.t, sample.accel, sample.gravity, sample.gyro, sample.fix)
                        ?: continue
                    emitted++
                    if (state.mode != NavMode.AIDED) sawBlackout = true
                    if (row == exitRow) atExit = state
                    if (row % trackStride == 0 && row / trackStride < track.length()) {
                        val p = track.getJSONArray(row / trackStride)
                        val gap = hypot(state.east - p.getDouble(0),
                                        state.north - p.getDouble(1))
                        if (gap > worstGap) { worstGap = gap; worstRow = row }
                        if (firstDivergeRow < 0 && gap > 5.0) firstDivergeRow = row
                        if (row / trackStride < 8) earlyGaps.append(
                            " r$row=${"%.1f".format(gap)}m(dev ${"%.1f".format(state.east)}," +
                            "${"%.1f".format(state.north)} vs ${p.getDouble(0)},${p.getDouble(1)})")
                    }
                    last = state
                }
            }

            assertTrue("${fixture.label}: no navigation states were produced at all", emitted > 1000)
            assertTrue("${fixture.label}: the state machine never noticed the outage", sawBlackout)
            // Reported before the endpoint assertions so a failure says where the port
            // first parted company with the desktop, not merely that it did.
            // The two implementations agree to a few centimetres over the whole replay,
            // outage and re-acquisition included, so this bound is loose enough to survive
            // floating-point reordering and tight enough that any real behavioural change
            // trips it. It was 15-25 m before the bearing accuracy was carried through and
            // the timestamp-threshold decimator was replaced.
            assertTrue("${fixture.label}: port diverges from the desktop track: worst gap " +
                "${"%.4f".format(worstGap)} m at row $worstRow, first exceeded 5 m at row " +
                "$firstDivergeRow (outage rows ${blackout.getInt("first_row")}-$exitRow)." +
                " early:$earlyGaps",
                worstGap < 0.1)
            val exit = atExit ?: error("replay ended before the outage did")

            // 1 m over a 1.36 km outage is 0.07% of the distance the drift metric divides
            // by; anything larger would mean a real difference in the mechanization rather
            // than accumulated floating-point noise.
            assertEquals("${fixture.label}: east at outage exit",
                expected.getDouble("east_at_exit_m"), exit.east, 0.1)
            assertEquals("${fixture.label}: north at outage exit",
                expected.getDouble("north_at_exit_m"), exit.north, 0.1)
            assertEquals("${fixture.label}: speed at outage exit",
                expected.getDouble("speed_at_exit_ms"), exit.speed, 0.01)
            assertEquals("${fixture.label}: heading at outage exit",
                expected.getDouble("heading_at_exit_deg"),
                (Math.toDegrees(exit.heading) + 360.0) % 360.0, 0.05)
            assertEquals("${fixture.label}: reported uncertainty at outage exit",
                expected.getDouble("sigma_at_exit_m"), exit.sigmaM, 0.5)

            val end = last ?: error("no states emitted")
            assertEquals("${fixture.label}: east at end of replay",
                expected.getDouble("east_at_end_m"), end.east, 0.1)
            assertEquals("${fixture.label}: north at end of replay",
                expected.getDouble("north_at_end_m"), end.north, 0.1)
        }
    }

    /**
     * The displayed track must never teleport, however far the estimate jumps.
     *
     * This is the section 9.2 requirement that recovery happens "without discontinuity in
     * the map display", and it is the one an audience actually sees.
     */
    @Test
    fun displayedTrackNeverTeleports() {
        val runtime = RuntimeConfig.fromAsset(context)
        SpeedModel(context, runtime).use { model ->
            val navigator = Navigator(runtime, model)
            navigator.overrideCalibration(desktopAlignment())

            var prevE = Double.NaN
            var prevN = Double.NaN
            var maxDisplayStep = 0.0
            var maxEstimateStep = 0.0
            var prevEstE = Double.NaN
            var prevEstN = Double.NaN

            ReplaySource(replay()).use { source ->
                source.runAll(navigator) { s ->
                    if (!prevE.isNaN()) {
                        maxDisplayStep = maxOf(maxDisplayStep,
                            hypot(s.displayEast - prevE, s.displayNorth - prevN))
                        maxEstimateStep = maxOf(maxEstimateStep,
                            hypot(s.east - prevEstE, s.north - prevEstN))
                    }
                    prevE = s.displayEast; prevN = s.displayNorth
                    prevEstE = s.east; prevEstN = s.north
                }
            }

            // the estimate is allowed -- required, even -- to snap; the display is not
            assertTrue("the estimate never jumped, so this test proved nothing " +
                "(max estimate step ${"%.1f".format(maxEstimateStep)} m)",
                maxEstimateStep > 50.0)
            // 200 m/s cap at 10 Hz is 20 m of travel in one displayed step
            assertTrue("displayed track jumped ${"%.1f".format(maxDisplayStep)} m in one " +
                "sample; the slew limiter is not doing its job",
                maxDisplayStep <= 21.0)
        }
    }

    /**
     * A phone's ~1 Hz GNSS callback is not phase-locked to its ~100 Hz accelerometer.
     * Every possible callback phase must therefore reach the 10 Hz navigation cycle.
     *
     * The live drive that motivated this test repeatedly entered false blackouts because
     * fixes on phases 1..9 were cleared before the decimator emitted. The performance
     * benchmark only put fixes on phase 0, so it could not expose that scheduling bug.
     */
    @Test
    fun liveGnssFixSurvivesEveryDecimationPhase() {
        val runtime = RuntimeConfig.fromAsset(context)
        val baseLat = 28.45
        val baseLon = 77.50
        val earthRadiusM = 6_378_137.0
        val accel = doubleArrayOf(0.0, 0.0, 9.81)
        val gravity = doubleArrayOf(0.0, 0.0, 9.81)
        val gyro = doubleArrayOf(0.0, 0.0, 0.0)
        val alignment = Alignment(
            forwardAngleRad = 0.0,
            forwardAccelScale = 1.0,
            gyroBiasRadS = 0.0,
            yawChannel = 2,
            yawScale = 1.0,
            forwardAccelCorr = 1.0,
            yawCorr = 1.0,
            samples = 1_000,
            baselines = 1_000,
        )

        for (phase in 0 until 10) {
            val navigator = Navigator(runtime, model = null, inputRateHz = 100.0)
            navigator.overrideCalibration(alignment)
            navigator.setOrigin(baseLat, baseLon, 0.0)

            fun fixAt(t: Double) = GnssFix(
                lat = baseLat + Math.toDegrees(10.0 * t / earthRadiusM),
                lon = baseLon,
                alt = 0.0,
                speed = 10.0,
                accuracyM = 3.0,
                bearingDeg = 0.0,
                bearingAccuracyDeg = 2.0,
            )

            var last: Navigator.State? = navigator.addSample(
                0.0, accel, gravity, gyro, fixAt(0.0)
            )
            for (callback in 1..800) {
                val t = callback / 100.0
                val fresh = callback >= 100 && (callback - phase) % 100 == 0
                navigator.addSample(
                    t, accel, gravity, gyro, if (fresh) fixAt(t) else null
                )?.let { last = it }
            }

            val end = last ?: error("phase $phase emitted no state")
            assertEquals("phase $phase falsely entered a GNSS outage", NavMode.AIDED, end.mode)
            assertTrue(
                "phase $phase fused too few GNSS measurements (${end.gnssUpdates})",
                end.gnssUpdates >= 7,
            )
            assertTrue(
                "phase $phase accumulated implausible uncertainty ${end.sigmaM} m",
                end.sigmaM < 10.0,
            )
        }
    }

    /**
     * A field blackout must drop fixes only at the estimator boundary. The same fixes stay
     * available as a reference, the normal three-second detector enters BLACKOUT, and
     * three returning fixes close REACQUIRING without any special estimator shortcut.
     */
    @Test
    fun controlledFieldBlackoutWithholdsReferenceAndReacquires() {
        val runtime = RuntimeConfig.fromAsset(context)
        val baseLat = 28.45
        val baseLon = 77.50
        val earthRadiusM = 6_378_137.0
        val accel = doubleArrayOf(0.0, 0.0, 9.81)
        val gravity = doubleArrayOf(0.0, 0.0, 9.81)
        val gyro = doubleArrayOf(0.0, 0.0, 0.0)
        val navigator = Navigator(runtime, model = null, inputRateHz = 100.0).apply {
            overrideCalibration(Alignment(
                forwardAngleRad = 0.0,
                forwardAccelScale = 1.0,
                gyroBiasRadS = 0.0,
                yawChannel = 2,
                yawScale = 1.0,
                forwardAccelCorr = 1.0,
                yawCorr = 1.0,
                samples = 1_000,
                baselines = 1_000,
            ))
        }
        val fieldTest = FieldBlackoutTest()
        assertTrue(fieldTest.arm(durationS = 6.0, aidedLeadInS = 1.0))
        var sawBlackout = false
        var sawReacquiring = false

        for (callback in 0..1_100) {
            val t = callback / 100.0
            fieldTest.beforeSample(t, navigator.state?.phase)
            var fix = if (callback % 100 == 0) GnssFix(
                lat = baseLat + Math.toDegrees(10.0 * t / earthRadiusM),
                lon = baseLon,
                alt = 0.0,
                speed = 10.0,
                accuracyM = 3.0,
                bearingDeg = 0.0,
                bearingAccuracyDeg = 2.0,
            ) else null
            if (fix != null && fieldTest.observeFix(t, fix, navigator)) fix = null
            navigator.addSample(t, accel, gravity, gyro, fix)?.let { state ->
                fieldTest.observeState(state)
                if (state.mode == NavMode.BLACKOUT) sawBlackout = true
                if (state.mode == NavMode.REACQUIRING) sawReacquiring = true
            }
        }

        val result = fieldTest.snapshot(11.0)
        assertEquals(FieldBlackoutPhase.COMPLETE, result.phase)
        assertTrue("controlled test never entered BLACKOUT", sawBlackout)
        assertTrue("controlled test skipped REACQUIRING", sawReacquiring)
        assertTrue("too few fixes were withheld: ${result.withheldFixes}",
            result.withheldFixes >= 5)
        assertTrue("hidden GNSS was not retained as reference", result.referenceSamples >= 5)
        assertTrue("test did not report recovery", result.recovered)
        assertTrue("synthetic constant-speed outage drifted ${result.endReferenceErrorM} m",
            result.endReferenceErrorM < 5.0)
    }

    /**
     * Live yaw must use every 100 Hz callback and apply the calibrated bias exactly once.
     *
     * The 10 Hz cosine is deliberately adversarial: taking every tenth gyro sample sees the
     * same positive peak forever, while integrating all ten samples cancels it. This is the
     * scheduling pattern that the first physical blackout exposed.
     */
    @Test
    fun nativeYawPreintegrationRejectsAliasingAndSubtractsBiasOnce() {
        val runtime = RuntimeConfig.fromAsset(context)
        val baseLat = 28.45
        val baseLon = 77.50
        val gravity = doubleArrayOf(0.0, 0.0, 9.80665)
        val accel = gravity.copyOf()
        val trueYawRate = 0.05
        val gyroBias = 0.01
        val aliasAmplitude = 0.20
        val durationS = 20.0
        val navigator = Navigator(runtime, model = null, inputRateHz = 100.0).apply {
            overrideCalibration(
                Alignment(
                    forwardAngleRad = 0.0,
                    forwardAccelScale = 1.0,
                    gyroBiasRadS = gyroBias,
                    yawChannel = 2,
                    yawScale = -1.0,
                    forwardAccelCorr = 1.0,
                    yawCorr = 1.0,
                    samples = 1_000,
                    baselines = 1_000,
                ),
                source = HeadingRateSource.GRAVITY_PROJECTED,
            )
        }

        var last: Navigator.State? = null
        for (callback in 0..(durationS * 100).toInt()) {
            val t = callback / 100.0
            val rawHeadingRate = trueYawRate + gyroBias +
                aliasAmplitude * cos(2.0 * Math.PI * 10.0 * t)
            // Compass heading is clockwise; Android gyro about device-up is opposite.
            val gyro = doubleArrayOf(0.0, 0.0, -rawHeadingRate)
            val fix = if (callback == 0) GnssFix(
                lat = baseLat,
                lon = baseLon,
                alt = 0.0,
                speed = 10.0,
                accuracyM = 3.0,
                bearingDeg = 0.0,
                bearingAccuracyDeg = 2.0,
            ) else null
            navigator.addSample(t, accel, gravity, gyro, fix)?.let { last = it }
        }

        val end = last ?: error("live-rate regression emitted no state")
        val expected = trueYawRate * durationS
        val headingError = abs(org.neuronavx.logger.nav.Signals.wrapAngle(end.heading - expected))
        assertEquals(HeadingRateSource.GRAVITY_PROJECTED, end.headingRateSource)
        assertTrue(
            "full-rate yaw/bias regression missed by ${Math.toDegrees(headingError)} deg",
            Math.toDegrees(headingError) < 1.0,
        )
    }

    /**
     * Aided course is allowed to correct heading, but it must not turn a short mismatch
     * between phone rotation and vehicle course into a permanent gyro bias/scale change.
     * The September field run began its outage correctly and ended 145 degrees wrong after
     * this hidden state escaped the calibration bounds.
     */
    @Test
    fun nativeHeadingKeepsCalibratedBiasAndUnitScale() {
        val runtime = RuntimeConfig.fromAsset(context)
        val gravity = doubleArrayOf(0.0, 0.0, 9.80665)
        val accel = gravity.copyOf()
        val calibratedBias = 0.01
        val navigator = Navigator(runtime, model = null, inputRateHz = 100.0).apply {
            overrideCalibration(
                Alignment(
                    forwardAngleRad = 0.0,
                    forwardAccelScale = 1.0,
                    gyroBiasRadS = calibratedBias,
                    yawChannel = 2,
                    yawScale = -1.0,
                    forwardAccelCorr = 1.0,
                    yawCorr = 1.0,
                    samples = 1_000,
                    baselines = 1_000,
                ),
                source = HeadingRateSource.GRAVITY_PROJECTED,
            )
        }

        var atLastFix: Navigator.State? = null
        var end: Navigator.State? = null
        for (callback in 0..3_500) {
            val t = callback / 100.0
            // Projection returns +calibratedBias, so fixed-bias propagation is stationary.
            val gyro = doubleArrayOf(0.0, 0.0, -calibratedBias)
            val fix = if (callback <= 1_500 && callback % 100 == 0) {
                val second = callback / 100
                GnssFix(
                    lat = 28.45,
                    lon = 77.50,
                    alt = 0.0,
                    speed = 10.0,
                    accuracyM = 3.0,
                    // Deliberately disagrees with the fixed phone gyro by 5 deg/s.
                    bearingDeg = second * 5.0,
                    bearingAccuracyDeg = 2.0,
                )
            } else null
            navigator.addSample(t, accel, gravity, gyro, fix)?.let { state ->
                if (callback == 1_500) atLastFix = state
                end = state
            }
        }

        val aided = atLastFix ?: error("no state at the final aided fix")
        val dark = end ?: error("no final native state")
        assertEquals(calibratedBias, aided.gyroBiasRadS, 1e-12)
        assertEquals(calibratedBias, dark.gyroBiasRadS, 1e-12)
        assertEquals(0.0, aided.gyroScaleError, 1e-12)
        assertEquals(0.0, dark.gyroScaleError, 1e-12)
        val darkHeadingError = abs(
            org.neuronavx.logger.nav.Signals.wrapAngle(dark.heading - aided.heading)
        )
        assertTrue(
            "fixed native heading drifted ${Math.toDegrees(darkHeadingError)} deg after aiding",
            Math.toDegrees(darkHeadingError) < 0.5,
        )
    }

    @Test
    fun liveSpeedAdapterRemovesAidedModelBias() {
        val adapter = LiveSpeedAdapter()
        val gnss = listOf(4.8, 5.1, 5.0, 5.2, 4.9, 5.0)
        val raw = listOf(9.7, 10.1, 10.2, 10.0, 9.8, 10.1)
        for (i in gnss.indices) {
            adapter.observeTrustedSpeed(i.toDouble(), gnss[i], 3.0)
            assertTrue(
                adapter.observeAidedPrediction(SpeedEstimate(raw[i], 2.0), gnss[i], 3.0)
            )
        }

        assertTrue("adapter did not earn calibration", adapter.isReady)
        assertEquals(6, adapter.calibrationSamples)
        assertEquals(5.0, adapter.biasMs, 0.25)
        val corrected = adapter.adapt(7.0, SpeedEstimate(10.8, 2.0))
        assertEquals("stable model bias was not removed", 5.8, corrected.speed, 0.35)
        assertTrue("corrected uncertainty ignored the aided residual",
            corrected.sigma >= adapter.residualSigmaMs)
    }

    @Test
    fun liveSpeedAdapterFallsBackUntilReadyAndLimitsJumps() {
        val fallback = LiveSpeedAdapter()
        fallback.observeTrustedSpeed(0.0, 4.0, 3.0)
        fallback.observeAidedPrediction(SpeedEstimate(14.0, 1.0), 4.0, 3.0)
        val uncalibrated = fallback.adapt(1.0, SpeedEstimate(25.0, 1.0))
        assertEquals("uncalibrated model replaced trusted speed", 4.0, uncalibrated.speed, 1e-9)
        assertTrue("uncalibrated fallback is overconfident", uncalibrated.sigma >= 6.0)

        val guarded = LiveSpeedAdapter()
        repeat(5) { i ->
            guarded.observeTrustedSpeed(i.toDouble(), 5.0, 3.0)
            guarded.observeAidedPrediction(SpeedEstimate(10.0, 1.0), 5.0, 3.0)
        }
        val normal = guarded.adapt(5.0, SpeedEstimate(10.0, 1.0))
        val jump = guarded.adapt(6.0, SpeedEstimate(30.0, 1.0))
        assertEquals(5.0, normal.speed, 1e-9)
        assertTrue("model jump exceeded the 3 m/s² acceleration guard",
            jump.speed <= normal.speed + 3.0 + 1e-9)
        assertTrue("clipped model jump did not increase uncertainty", jump.sigma >= 17.0)
    }

    /** Regression for the two September 3 drives: raw TCN speed was consistently +5 m/s. */
    @Test
    fun nativeNavigationCalibratesBiasedModelBeforeBlackout() {
        val runtime = RuntimeConfig.fromAsset(context)
        val biasedModel = SpeedPredictionModel { SpeedEstimate(speed = 10.0, sigma = 2.0) }
        val baseLat = 28.45
        val baseLon = 77.50
        val earthRadiusM = 6_378_137.0
        val trueSpeed = 5.0
        val gravity = doubleArrayOf(0.0, 0.0, 9.80665)
        val navigator = Navigator(
            runtime,
            model = biasedModel,
            inputRateHz = 100.0,
        ).apply {
            overrideCalibration(
                Alignment(
                    forwardAngleRad = 0.0,
                    forwardAccelScale = 1.0,
                    gyroBiasRadS = 0.0,
                    yawChannel = 2,
                    yawScale = -1.0,
                    forwardAccelCorr = 1.0,
                    yawCorr = 1.0,
                    samples = 1_000,
                    baselines = 1_000,
                ),
                source = HeadingRateSource.GRAVITY_PROJECTED,
            )
        }

        var end: Navigator.State? = null
        for (callback in 0..7_500) {
            val t = callback / 100.0
            val fix = if (callback <= 1_200 && callback % 100 == 0) GnssFix(
                lat = baseLat + Math.toDegrees(trueSpeed * t / earthRadiusM),
                lon = baseLon,
                alt = 0.0,
                speed = trueSpeed,
                accuracyM = 3.0,
                bearingDeg = 0.0,
                bearingAccuracyDeg = 2.0,
            ) else null
            navigator.addSample(
                t,
                gravity,
                gravity,
                doubleArrayOf(0.0, 0.0, 0.0),
                fix,
            )?.let { end = it }
        }

        val state = end ?: error("biased-model regression emitted no state")
        assertEquals(NavMode.BLACKOUT, state.mode)
        assertTrue("too few aided model/GNSS pairs: ${state.speedModelCalibrationSamples}",
            state.speedModelCalibrationSamples >= 5)
        assertEquals(5.0, state.speedModelBiasMs, 1e-9)
        assertEquals(10.0, state.learnedSpeed, 1e-9)
        assertEquals(5.0, state.adaptedSpeed, 1e-9)
        assertEquals("biased learned speed leaked into the EKF", trueSpeed, state.speed, 0.2)
        val expectedNorth = trueSpeed * state.t
        assertTrue(
            "bias-corrected blackout drifted ${abs(state.north - expectedNorth)} m",
            abs(state.north - expectedNorth) < 10.0,
        )
    }

    @Test
    fun gravityProjectedYawSurvivesPhoneTilt() {
        val trueYawRate = 0.2
        val tilts = listOf(
            doubleArrayOf(0.0, 0.0, 1.0),
            doubleArrayOf(0.06, 0.34, 0.94),
            doubleArrayOf(-0.31, 0.18, 0.93),
        )
        for (up in tilts) {
            val norm = kotlin.math.sqrt(up.sumOf { it * it })
            val gravity = DoubleArray(3) { up[it] / norm * 9.80665 }
            val gyro = DoubleArray(3) { -trueYawRate * up[it] / norm }
            assertEquals(
                trueYawRate,
                org.neuronavx.logger.nav.Signals.gravityProjectedHeadingRate(gyro, gravity),
                1e-9,
            )
        }
    }

    /**
     * With a tilted phone, two raw gyro axes can be equally good descriptions of the turn.
     * Live Android does not need to choose between them because gravity projection combines
     * them physically; a raw-axis winner-margin gate must therefore not block calibration.
     */
    @Test
    fun gravityProjectedCalibrationIgnoresRawAxisTie() {
        val calibration = OnlineCalibration(useGravityProjectedYaw = true)
        calibration.setRate(100.0)
        val rootHalf = sqrt(0.5)
        val up = doubleArrayOf(0.0, rootHalf, rootHalf)
        val gravity = DoubleArray(3) { up[it] * 9.80665 }
        val projectedBias = 0.002
        var trueHeading = 0.0
        var previousFixSpeed = Double.NaN
        var heldForwardAcceleration = 0.0

        for (callback in 0..13_000) {
            val t = callback / 100.0
            if (callback % 100 == 0) {
                val speed = 10.0 + 2.0 * sin(t / 8.0)
                if (previousFixSpeed.isFinite()) {
                    heldForwardAcceleration = speed - previousFixSpeed
                }
                previousFixSpeed = speed
                calibration.addFix(t, speed, trueHeading)
            }

            val trueYawRate = 0.08 * sin(t / 5.0) + 0.03 * cos(t / 11.0)
            val measured = trueYawRate + projectedBias
            // gy and gz are identical, so their raw correlations tie exactly.
            val gyro = DoubleArray(3) { -measured * up[it] }
            val lateralAcceleration = 0.4 * sin(t / 3.0)
            val accel = gravity.copyOf().also {
                it[0] += heldForwardAcceleration
                // e2 = up x device-X = (0, +sqrt(1/2), -sqrt(1/2)). A small
                // independent lateral signal keeps the 2-D forward fit non-degenerate.
                it[1] += lateralAcceleration * rootHalf
                it[2] -= lateralAcceleration * rootHalf
            }
            calibration.addImu(t, accel, gravity, gyro)
            trueHeading = org.neuronavx.logger.nav.Signals.wrapAngle(
                trueHeading + trueYawRate / 100.0
            )
        }

        val solved = calibration.solve()
        assertTrue(
            "projected calibration rejected a raw-axis tie " +
                "(${calibration.yawBaselines} baselines; ${calibration.lastRejectionReason})",
            solved != null,
        )
        val alignment = solved!!
        assertTrue("projected yaw correlation ${alignment.yawCorr} is weak",
            alignment.yawCorr > 0.95)
        assertEquals(projectedBias, alignment.gyroBiasRadS, 5e-4)
    }

    /**
     * Does the ONLINE calibration reach the constants the desktop computed offline?
     *
     * This is checked separately and with loose bounds on purpose. The desktop fits over a
     * whole session with a centred smoother; the phone accumulates causally from nothing.
     * What matters for navigation is the yaw channel (categorical -- getting it wrong is
     * catastrophic) and the yaw scale, which integrates directly into heading.
     */
    @Test
    fun onlineCalibrationRecoversTheDesktopConstants() {
        val desktop = desktopAlignment()
        val calibration = OnlineCalibration()
        calibration.setRate(10.0)

        ReplaySource(replay()).use { source ->
            while (true) {
                val s = source.next() ?: break
                s.fix?.let {
                    calibration.addFix(s.t, it.speed,
                        if (it.bearingDeg.isFinite()) Math.toRadians(it.bearingDeg)
                        else Double.NaN)
                }
                calibration.addImu(s.t, s.accel, s.gravity, s.gyro)
            }
        }

        val solved = calibration.solve()
        assertTrue("online calibration never converged on a log the desktop calibrated " +
            "(${calibration.angleSamples} angle samples, " +
            "${calibration.yawBaselines} yaw baselines; " +
            "${calibration.lastRejectionReason})", solved != null)
        val online = solved!!

        // The yaw channel is categorical and getting it wrong inverts every turn.
        assertEquals("yaw channel", desktop.yawChannel, online.yawChannel)
        // Scale multiplies every turn, so it integrates straight into heading.
        assertTrue("yaw scale ${online.yawScale} is not within 10% of the session's " +
            "${desktop.yawScale}",
            abs(online.yawScale - desktop.yawScale) <= 0.10 * abs(desktop.yawScale))
        // Bias accumulates with elapsed time: 0.002 rad/s is 14 deg over a 120 s outage,
        // which is the most a blackout should ever be asked to absorb from calibration.
        assertTrue("gyro bias ${online.gyroBiasRadS} differs from the session's " +
            "${desktop.gyroBiasRadS} by more than 0.002 rad/s",
            abs(online.gyroBiasRadS - desktop.gyroBiasRadS) < 0.002)

        // The forward AXIS is deliberately not asserted. Measured on the desktop, it needs
        // far more aided driving than the yaw terms: on a 13-minute window it lands ~37 deg
        // from the whole-session answer. That is a real deployment limitation, recorded
        // here rather than papered over -- the app must keep calibrating as it drives, and
        // must not present a converged forward scale early.
        println("forward angle: online ${Math.toDegrees(online.forwardAngleRad)} deg, " +
            "session ${Math.toDegrees(desktop.forwardAngleRad)} deg; " +
            "scale ${online.forwardAccelScale} vs ${desktop.forwardAccelScale}")
    }

    /**
     * How long does one full navigation update take on this device?
     *
     * Gate 5 asks for the target update rate "with the complete sensor/fusion loop active",
     * not for the network in isolation, and until this phase there was no loop to measure --
     * `SpeedModelBenchmark` timed the graph against random input. This times what actually
     * runs: feature construction, the ES-EKF propagate and updates, the blackout state
     * machine, the track smoother, and the network at its 1 Hz fusion cadence.
     *
     * An emulator figure does not close the gate. It does establish the margin and would
     * catch a change that made the loop quadratic in the length of the drive.
     */
    @Test
    fun fullNavigationLoopFitsTheUpdateBudget() {
        val result = FullNavigationLoopBenchmark(context).use {
            it.run(repeats = 1, sensorRateHz = 100.0)
        }
        println("navigation loop on this device:\n$result")
        assertTrue("benchmark did not exercise the unaided loop", result.unaidedCycles > 1000)
        assertTrue("median update %.3f ms exceeds half the %.1f ms budget"
            .format(result.medianMs, result.budgetMs), result.medianMs < result.budgetMs / 2)
        assertTrue("p95 update %.3f ms exceeds the %.1f ms budget"
            .format(result.p95Ms, result.budgetMs), result.p95Ms < result.budgetMs)
    }

    companion object {
        private val M_SEG00 = ReplayFixture(
            label = "B/M_seg00",
            csvAsset = "replay_M_seg00.csv",
            sidecarAsset = "replay_M_seg00.json",
            csvShipsWithApp = true,
        )
        private val M_SEG01 = ReplayFixture(
            label = "B/M_seg01",
            csvAsset = "replay_M_seg01.csv",
            sidecarAsset = "replay_M_seg01.json",
        )
        private val S1_SEG00 = ReplayFixture(
            label = "A/S1_seg00",
            csvAsset = "replay_S1_seg00.csv",
            sidecarAsset = "replay_S1_seg00.json",
        )
    }
}
